config/routes.rb
Rails.application.routes.draw do
  resources :explores
  root 'home#index'
  #get 'home#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/explore.rb
class Explore < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/explores_controller.rb
class ExploresController < ApplicationController
  before_action :set_explore, only: [:show, :edit, :update, :destroy]

  # GET /explores
  # GET /explores.json
  def index
    @explores = Explore.all
  end

  # GET /explores/1
  # GET /explores/1.json
  def show
  end

  # GET /explores/new
  def new
    @explore = Explore.new
  end

  # GET /explores/1/edit
  def edit
  end

  # POST /explores
  # POST /explores.json
  def create
    @explore = Explore.new(explore_params)

    respond_to do |format|
      if @explore.save
        format.html { redirect_to @explore, notice: 'Explore was successfully created.' }
        format.json { render :show, status: :created, location: @explore }
      else
        format.html { render :new }
        format.json { render json: @explore.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /explores/1
  # PATCH/PUT /explores/1.json
  def update
    respond_to do |format|
      if @explore.update(explore_params)
        format.html { redirect_to @explore, notice: 'Explore was successfully updated.' }
        format.json { render :show, status: :ok, location: @explore }
      else
        format.html { render :edit }
        format.json { render json: @explore.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /explores/1
  # DELETE /explores/1.json
  def destroy
    @explore.destroy
    respond_to do |format|
      format.html { redirect_to explores_url, notice: 'Explore was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_explore
      @explore = Explore.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def explore_params
      params.fetch(:explore, {})
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/explores_helper.rb
module ExploresHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/explores/_form.html.erb
<%= form_for(explore) do |f| %>
  <% if explore.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(explore.errors.count, "error") %> prohibited this explore from being saved:</h2>

      <ul>
      <% explore.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/explores/edit.html.erb
<h1>Editing Explore</h1>

<%= render 'form', explore: @explore %>

<%= link_to 'Show', @explore %> |
<%= link_to 'Back', explores_path %>

app/views/explores/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Explores</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @explores.each do |explore| %>
      <tr>
        <td><%= link_to 'Show', explore %></td>
        <td><%= link_to 'Edit', edit_explore_path(explore) %></td>
        <td><%= link_to 'Destroy', explore, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Explore', new_explore_path %>

app/views/explores/new.html.erb
<h1>New Explore</h1>

<%= render 'form', explore: @explore %>

<%= link_to 'Back', explores_path %>

app/views/home/index.html.erb
		<section class="page-title style1 parallax parallax1">
			<div class="container">
				<div class="row">
					<div class="col-md-12">
						<div class="wrap-box-search style1">
							<form action="#" method="get" accept-charset="utf-8">
								<span>
									<input type="text" placeholder="What are you looking for ?" name="search">
								</span>
								<span class="location">
									<span class="ti-location-pin"></span>
									<input type="text" placeholder="Location" name="location">
								</span>
								<span class="categories">
									<span class="ti-angle-down"></span>
									<select name="categories">
										<option value="">All Categories</option>
										<option value="">All Categories</option>
										<option value="">All Categories</option>
									</select>
								</span>
								<button type="submit" class="search-btn">Search</button>
							</form><!-- /form -->
						</div><!-- /.wrap-box-search -->
					</div><!-- /.col-md-12 -->
				</div><!-- /.row -->
			</div><!-- /.container -->
			<div class="overlay"></div>
		</section><!-- /.page-title -->

		<section class="flat-row flat-imagebox style3">
			<div class="container">
				<div class="row">
					<div class="col-md-12">
						<div class="filter style2">
							<div class="filter-title">
								<h5>Filter by tag:</h5>
								<span class="ti-angle-down"></span>
							</div>
							<div class="clearfix"></div>
							<div class="select-filter">
								<ul class="list-filter quarter">
									<li class="active">
										<span class="ti-check-box"></span>Wireless Internet
									</li>
									<li>
										<span class="ti-layout-width-full"></span>Street Parking
									</li>
									<li>
										<span class="ti-layout-width-full"></span>Kitchen
									</li>
									<li class="active">
										<span class="ti-check-box"></span>Bike Parking
									</li>
								</ul>
								<ul class="list-filter quarter">
									<li>
										<span class="ti-layout-width-full"></span>Pets Friendly
									</li>
									<li>
										<span class="ti-layout-width-full"></span>Cable TV
									</li>
									<li class="active">
										<span class="ti-check-box"></span>Smoking Allowed
									</li>
									<li>
										<span class="ti-layout-width-full"></span>Good for Kids
									</li>
								</ul>
								<ul class="list-filter quarter">
									<li>
										<span class="ti-layout-width-full"></span>Pool
									</li>
									<li>
										<span class="ti-layout-width-full"></span>Washer
									</li>
									<li>
										<span class="ti-layout-width-full"></span>Hair Dryer
									</li>
									<li>
										<span class="ti-layout-width-full"></span>Wheelchair Accessible
									</li>
								</ul>
								<ul class="list-filter quarter">
									<li>
										<span class="ti-layout-width-full"></span>Ultra High End
									</li>
									<li>
										<span class="ti-layout-width-full"></span>Pricey
									</li>
									<li class="active">
										<span class="ti-check-box"></span>Most Reviewed
									</li>
									<li>
										<span class="ti-layout-width-full"></span>Highest Rated
									</li>
								</ul>
								<div class="clearfix"></div>
							</div><!-- /.select-filter -->
						</div><!-- /.filter -->
						<div class="filter-result style2">
							<div class="result">
								5 Results Found
							</div>
							<ul class="arrange">
								<li class="active">
									<span class="ti-view-grid"></span>
								</li>
								<li>
									<span class="ti-view-list"></span>
								</li>
							</ul>
						</div><!-- /.filter-result -->
					</div><!-- /.col-md-12 -->
				</div><!-- /.row -->
				<div class="wrap-imagebox style3">
					<div class="row">
						<div class="col-sm-12">
							<div class="imagebox style2">
								<div class="box-imagebox">
									<div class="box-header">
										<div class="box-image">
											<img src="<%= asset_path 'page/img-v2-01.png' %>" alt="">
											<a href="#" title="">Preview</a>
										</div>
									</div><!-- /.box-header -->
									<div class="box-content">
										<div class="box-title ad">
											<span>Ad</span><a href="#" title="">AN Restaurant</a><i class="fa fa-check-circle" aria-hidden="true"></i>
											<div class="queue">
												<i class="fa fa-star" aria-hidden="true"></i>
												<i class="fa fa-star" aria-hidden="true"></i>
												<i class="fa fa-star" aria-hidden="true"></i>
												<i class="fa fa-star" aria-hidden="true"></i>
												<i class="fa fa-star-half-o" aria-hidden="true"></i>
											</div>
										</div>
										<ul class="rating">
											<li>5 rating</li>
											<li>Moderate</li>
											<li>Restaurant</li>
										</ul>
										<div class="box-desc">
											Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur.  
										</div>
										<ul class="location">
											<li class="address"><span class="ti-location-pin"></span>Hanoi, Vietnam</li>
											<li class="closed">Closed Now !</li>
										</ul>
									</div><!-- /.box-content -->
								</div><!-- /.box-imagebox -->
							</div><!-- /.imagebox style2 -->
						</div><!-- /.col-sm-12 -->
						<div class="col-sm-12">
							<div class="imagebox style2">
								<div class="box-imagebox">
									<div class="box-header">
										<div class="box-image">
											<img src="<%= asset_path 'page/img-v2-02.png' %>" alt="">
											<a href="#" title="">Preview</a>
										</div>
									</div><!-- /.box-header -->
									<div class="box-content">
										<div class="box-title">
											<a href="#" title="">Acantara</a><i class="fa fa-check-circle" aria-hidden="true"></i>
											<div class="queue">
												<i class="fa fa-star" aria-hidden="true"></i>
												<i class="fa fa-star" aria-hidden="true"></i>
												<i class="fa fa-star" aria-hidden="true"></i>
												<i class="fa fa-star" aria-hidden="true"></i>
												<i class="fa fa-star" aria-hidden="true"></i>
											</div>
										</div>
										<ul class="rating">
											<li>10 rating</li>
											<li>Ultra High End</li>
											<li>Hotel</li>
										</ul>
										<div class="box-desc">
											Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur.
										</div>
										<ul class="location">
											<li class="address"><span class="ti-location-pin"></span>Seoul, Korea</li>
											<li class="open">Open Now !</li>
										</ul>
									</div><!-- /.box-content -->
								</div><!-- /.box-imagebox -->
							</div><!-- /.imagebox style2 -->
						</div><!-- /.col-sm-12 -->
						<div class="col-sm-12">
							<div class="imagebox style2">
								<div class="box-imagebox">
									<div class="box-header">
										<div class="box-image">
											<img src="<%= asset_path 'page/img-v2-03.png' %>" alt="">
											<a href="#" title="">Preview</a>
										</div>
									</div><!-- /.box-header -->
									<div class="box-content">
										<div class="box-title">
											<a href="#" title="">Intercontinental</a><i class="fa fa-check-circle" aria-hidden="true"></i>
											<div class="queue">
												<i class="fa fa-star" aria-hidden="true"></i>
												<i class="fa fa-star" aria-hidden="true"></i>
												<i class="fa fa-star" aria-hidden="true"></i>
												<i class="fa fa-star" aria-hidden="true"></i>
												<i class="fa fa-star" aria-hidden="true"></i>
											</div>
										</div>
										<ul class="rating">
											<li>6 rating</li>
											<li>Pricey</li>
											<li>Hotel</li>
										</ul>
										<div class="box-desc">
											Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur.
										</div>
										<ul class="location">
											<li class="address"><span class="ti-location-pin"></span>Seoul, Korea</li>
											<li class="open">Open Now !</li>
										</ul>
									</div><!-- /.box-content -->
								</div><!-- /.box-imagebox -->
							</div><!-- /.imagebox style2 -->
						</div><!-- /.col-sm-12 -->
						<div class="col-sm-12">
							<div class="imagebox style2">
								<div class="box-imagebox">
									<div class="box-header">
										<div class="box-image">
											<img src="<%= asset_path 'page/img-v2-01.png' %>" alt="">
											<a href="#" title="">Preview</a>
										</div>
									</div><!-- /.box-header -->
									<div class="box-content">
										<div class="box-title ad">
											<span>Ad</span><a href="#" title="">AN Restaurant</a><i class="fa fa-check-circle" aria-hidden="true"></i>
											<div class="queue">
												<i class="fa fa-star" aria-hidden="true"></i>
												<i class="fa fa-star" aria-hidden="true"></i>
												<i class="fa fa-star" aria-hidden="true"></i>
												<i class="fa fa-star" aria-hidden="true"></i>
												<i class="fa fa-star-half-o" aria-hidden="true"></i>
											</div>
										</div>
										<ul class="rating">
											<li>5 rating</li>
											<li>Moderate</li>
											<li>Restaurant</li>
										</ul>
										<div class="box-desc">
											Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur.  
										</div>
										<ul class="location">
											<li class="address"><span class="ti-location-pin"></span>Hanoi, Vietnam</li>
											<li class="closed">Closed Now !</li>
										</ul>
									</div><!-- /.box-content -->
								</div><!-- /.box-imagebox -->
							</div><!-- /.imagebox style2 -->
						</div><!-- /.col-sm-12 -->
						<div class="col-sm-12">
							<div class="imagebox style2">
								<div class="box-imagebox">
									<div class="box-header">
										<div class="box-image">
											<img src="<%= asset_path 'page/img-v2-02.png' %>" alt="">
											<a href="#" title="">Preview</a>
										</div>
									</div><!-- /.box-header -->
									<div class="box-content">
										<div class="box-title">
											<a href="#" title="">Acantara</a><i class="fa fa-check-circle" aria-hidden="true"></i>
											<div class="queue">
												<i class="fa fa-star" aria-hidden="true"></i>
												<i class="fa fa-star" aria-hidden="true"></i>
												<i class="fa fa-star" aria-hidden="true"></i>
												<i class="fa fa-star" aria-hidden="true"></i>
												<i class="fa fa-star" aria-hidden="true"></i>
											</div>
										</div>
										<ul class="rating">
											<li>10 rating</li>
											<li>Ultra High End</li>
											<li>Hotel</li>
										</ul>
										<div class="box-desc">
											Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur.
										</div>
										<ul class="location">
											<li class="address"><span class="ti-location-pin"></span>Seoul, Korea</li>
											<li class="open">Open Now !</li>
										</ul>
									</div><!-- /.box-content -->
								</div><!-- /.box-imagebox -->
							</div><!-- /.imagebox style2 -->
						</div><!-- /.col-sm-12 -->
					</div><!-- /.row -->
					<div class="row">
						<div class="col-md-12">
							<div class="btn-more">
								<a href="#" title="">Show More</a>
							</div>
						</div>
					</div><!-- /.row -->
				</div>
			</div><!-- /.container -->
		</section><!-- /.flat-imagebox style3 -->

		<section class="flat-row flat-subscribe">
			<div class="container">
				<div class="row">
					<div class="col-sm-7">
						<div class="subscribe-text">
							Subscribe and be notified about new locations
						</div>
					</div><!-- /.col-sm-7 -->
					<div class="col-sm-5">
						<div class="subscribe-form">
							<form action="#" method="get" accept-charset="utf-8">
								<div class="subscribe-content">
									<div class="input-field">
										<input type="email" name="yourEmail" placeholder="Your Email" />
									</div>
									<button><span class="arrow_right"></span></button>
								</div>
							</form>
						</div><!-- /.subscribe-form -->
					</div><!-- /.col-sm-5 -->
				</div><!-- /.row -->
			</div><!-- /.container -->
		</section><!-- /.flat-subscibe -->
		
		<!-- panel content -->
		
		<% content_for 'javascript_content' do %>
		<%= javascript_include_tag params[:controller] %> <!-- include할 파일이 다 들어감 -->
		
        <script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyBtRmXKclfDp20TvfQnpgXSDPjut14x5wk&region=GB"></script>>
	       
	    </script>
		<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MyList</title>
    <%= csrf_meta_tags %>
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_link_tag    params[:controller], media: 'all' %>
    <%= javascript_include_tag 'application'%>
  </head>

  <body>
    <%= render 'shared/nav' %>
    <%= yield %>
    <%= render 'shared/footer' %>
    <%= yield 'javascript_content' %>
  </body>
</html>

app/views/shared/_footer.html.erb
	<footer>
			<div class="container">
				<div class="row">
					<div class="col-md-3">
						<div class="widget widget-about">
							<div class="logo-ft">
								<a href="#" title="">
									Dailylist
								</a>
							</div>
							<p>
								Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.
							</p>
						</div><!-- /.widget-about -->
					</div><!-- /.col-md-3 -->
					<div class="col-md-3">
						<div class="widget widget-categories">
							<h3 class="widget-title">Categories</h3>
							<ul class="one-half">
								<li>
									<a href="#" title="">Foot</a>
								</li>
								<li>
									<a href="#" title="">Hotel</a>
								</li>
								<li>
									<a href="#" title="">Play</a>
								</li>
								<li>
									<a href="#" title="">Automove</a>
								</li>
							</ul>
							<ul class="one-half">
								<li>
									<a href="#" title="">Shop</a>
								</li>
								<li>
									<a href="#" title="">Fitness</a>
								</li>
								<li>
									<a href="#" title="">Nightlife</a>
								</li>
								<li>
									<a href="#" title="">Park</a>
								</li>
							</ul>
							<div class="clearfix"></div>
						</div><!-- /.widget-categories -->
					</div><!-- /.col-md-3 -->
					<div class="col-md-3">
						<div class="widget widget-contact">
							<h3 class="widget-title">Contact</h3>
							<ul class="contact-infomation">
								<li class="address">
									PO Box 16122 Collins Street West Victoria 8007 Australia
								</li>
								<li class="phone">
									(84) 90 532 9119
								</li>
								<li class="email">
									Dailist.support@gmail.com
								</li>
							</ul>
						</div><!-- /.widget-contact -->
					</div><!-- /.col-md-3 -->
					<div class="col-md-3">
						<div class="widget widget-map">
							<img src="<%= asset_path 'page/bg-ft.png' %> " alt="">
						</div><!-- /.widget-map -->
					</div><!-- /.col-md-3 -->
				</div><!-- /.row -->
			</div><!-- /.container -->
		</footer><!-- /footer -->

app/views/shared/_nav.html.erb
		<div class="header">
			<div class="container-fluid">
				<div class="row">
					<div class="col-md-12">
						<div class="header-wrap">
							<div id="logo" class="logo">
								<a href="index.html" title="">
									Dailist
								</a>
							</div><!-- /.logo -->
							<div class="nav-wrap">
								<nav id="mainnav" class="mainnav">
									 <ul class="menu">
									 	<li>
									 		<a href="#" title="">Explore</a>
									 		<ul class="submenu">
									 			<li>
									 				<a href="explore-v1.html" title="">Explore Map Zoom In</a>
									 			</li>
									 			<li>
									 				<a href="explore-v2.html" title="">Explore Map Zoom Out</a>
									 			</li>
									 			<li>
									 				<a href="explore-v3.html" title="">Explore Map List</a>
									 			</li>
									 			<li>
									 				<a href="explore-v4.html" title="">Explore Grid</a>
									 			</li>
									 			<li>
									 				<a href="explore-v5.html" title="">Explore List</a>
									 			</li>
									 			<li>
									 				<a href="explore-detail.html" title="">Explore Details</a>
									 			</li>
									 		</ul>
									 	</li>
									 	<li>
									 		<a href="#" title="">Pages</a>
									 		<ul class="submenu">
									 			<li>
									 				<a href="index.html" title="">Index Layout</a>
									 			</li>
									 			<li>
									 				<a href="404.html" title="">404 Page</a>
									 			</li>
									 			<li>
									 				<a href="addlisting.html" title="">Add Listings</a>
									 			</li>
									 			<li>
									 				<a href="comingsoon.html" title="">Comming Soon</a>
									 			</li>
									 			<li>
									 				<a href="contact.html" title="">Contact</a>
									 			</li>
									 			<li>
									 				<a href="price.html" title="">Price Page</a>
									 			</li>
									 			<li>
									 				<a href="work.html" title="">How It Works</a>
									 			</li>
									 		</ul>
									 	</li>
									 	<li>
									 		<a href="blog.html" title="">Blog</a>
									 		<ul class="submenu">
									 			<li>
									 				<a href="blog.html" title="">Blog</a>
									 			</li>
									 			<li>
									 				<a href="blog-single.html" title="">Blog Single</a>
									 			</li>
									 		</ul>
									 	</li>
									 	<li>
									 		<a href="login.html" title="">Log In</a>
									 	</li>
									 	<li>
									 		<a href="register.html" title="">Sign Up</a>
									 	</li>
									 </ul>
								</nav><!-- /.mainnav -->
								<div class="button-header">
									<a href="http://corpthemes.com/html/dailist/register.html" title=""><i class="ti-plus"></i>Add Your Properties</a>
								</div>
								<div class="show-search">
									<button><span class="ti-search"></span></button>
									<div class="submenu top-search search-header">
					                    <form role="search" method="get" class="search-form" action="#">
											<label>
												<input type="search" class="search-field" placeholder="Search …" value="" name="search">
											</label>
											<button class="search-submit-form" title="Search now"><i class="fa fa-search" aria-hidden="true"></i></button>
										</form>                
									</div>
								</div><!-- /.show-search -->
								<div class="btn-menu">
		                            <span></span>
		                        </div><!-- //mobile menu button -->
							</div><!-- /.nav-wrap -->
						</div><!-- /.header-wrap -->
					</div><!-- /.col-md-12 -->
				</div><!-- /.row -->
			</div><!-- /.container-fluid -->
		</div><!-- /.header -->